use_frameworks!
platform :ios, '14.1'

target 'KeyValueData_Example' do
  pod 'KeyValueData', :path => '../'

  target 'KeyValueData_Tests' do
    inherit! :search_paths
    pod 'Nimble'
    
  end
end
